### ISSUE TITLE
Internal server Error: 500

### ISSUE THREAD

**Issue by YgorPerez** [nexxeln/ama#1]
# Steps to reproduce: 
open the link https://ama-tau.vercel.app/

---

## Error message: 

500: INTERNAL_SERVER_ERROR
Code: INTERNAL_FUNCTION_INVOCATION_FAILED
ID: gru1::4vt6x-1657774615828-9f06e54aca56

**Comment by nexxeln** [comment]
yes this project is dead haha. wasn't proud of the css so i abandoned it.
